name: Update Blocklist

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Run update script
        run: bash update.sh

      - name: Commit & Force Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add blocklist.netset
          git commit -m "auto update blocklist" || echo "no changes"

          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/slavsut/blocklist-repo.git HEAD:main
