name: Update Blocklist

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v5

      - name: Run update script
        run: bash update.sh

      - name: Push to blocklist branch
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          # создаём чистую ветку blocklist
          git checkout --orphan blocklist

          # удаляем всё кроме файла
          git rm -rf .

          # возвращаем файл
          mv blocklist.netset .

          git add blocklist.netset
          git commit -m "update blocklist"

          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/slavsut/blocklist-repo.git blocklist --force
