name: Update Blocklist

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Update system
        run: sudo apt-get update

      - name: Run script
        run: bash update.sh

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add blocklist.netset
          git commit -m "auto update" || echo "no changes"
          git push
